---
- name: Install firewall deb packages
  become: true
  ansible.builtin.apt:
    name: nftables
    state: present

- name: Create nftables directory
  become: true
  ansible.builtin.file:
    path: /etc/nftables
    mode: u=rwx,g=rx,o=rx
    state: directory

- name: Copy common firewall rules from template
  become: true
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: u=rwx,g=r,o=r
    validate: nft -c -f %s
  notify: Reload nftables

- name: Start and enable nftables service
  become: true
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
  async: 60
  when: not ansible_check_mode
  poll: 0
  register: nftables_service

- name: Check on nftables service
  become: true
  ansible.builtin.async_status:
    jid: "{{ nftables_service.ansible_job_id }}"
  register: nftables_service_result
  when: not ansible_check_mode
  until: nftables_service_result.finished
  retries: 12
  delay: 5
